const express= require('express')
const route = express.Router()
const LocationData = require("../controllers/locations")
const MealTypeData = require("../controllers/mealType")
const RestaurantData = require("../controllers/restaurants")
const userController = require("../controllers/UserController")
route.get("/",(req,res)=>{
    res.send("<h1>Welcome</h1>")
})
route.get("/getAllLocations",LocationData.getLocations)
route.get("/getAllRestaurants",RestaurantData.getRestaurants)
route.get("/getAllMealTypes",MealTypeData.getMealTypes)
route.get("/getAllRestaurants/:cityName",RestaurantData.getfilteredRestaurant)
route.get("/details",RestaurantData.getResData)
route.get("/Restaurants/:id",RestaurantData.getfilteredId)
route.post("/signup",userController.signup)
route.post("/login",userController.signin)
route.post("/restaurantfilter",RestaurantData.restaurantfilter)
module.exports = route